### ISSUE TITLE
Question about what to be include in the Algorithm, Documentation and Unit test.

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework1G2#27]
Do I have to include the state vector, probabilities or the Q-sphere graphs in the Algorithm or the unit test part??

What are the important things to be included??

**Comment by Pranjal-Srivastava-2023** [comment]
@yasmensarhan27 In the documentation we are basically explaining what our aim is and how we achieve that. It is like a summary of the algorithm used, code, and unit tests (results). So, I think state vector, probabilities or the Q-sphere graphs should go in the documentation because there you can explain what they mean and why you need them. We can read and benefit from it too!
